name: Go

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        name: run lint and tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache: false
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                version: v1.54
            - name: Run test
              run: go test -v ./...
